### ISSUE TITLE
Where is one-layer MLP being implemented?

### ISSUE THREAD

**Issue by ni9elf** [alexTsaptsinos/lyricsHAN#1]
Why is `l_dense_sent = TimeDistributed(Dense(200))(l_gru_sent)` commented in your code? Isn't the Dense layer needed for the one-layer MLP as mentioned in the HAN paper or is the line `ui = K.tanh(K.dot(x_reshaped, self.W) + self.bw)` in the attention layer taking care of this? Please clarify.

Thanks.

**Comment by alexTsaptsinos** [comment]
Hi Nigel,

Yes the custom `AttLayer` deals with the one layer MLP as you rightly pointed out in the line `ui = K.tanh(K.dot(x_reshaped, self.W) + self.bw)`. The commented line is leftover from playing around - I'll remove it now for future clarity.

Alex

**Comment by ni9elf** [comment]
Thanks Alex for the clarification. Any idea what was the original purpose of the Dense layer? I've seen it in another implementation too.

**Comment by alexTsaptsinos** [comment]
I think some people have tried adding an additional dense layer at that point (after attention) as well as the dense layer before attention is applied. I believe that was me just testing that there as well!
