### ISSUE TITLE
Code to Visualize Attention Weights

### ISSUE THREAD

**Issue by ni9elf** [alexTsaptsinos/lyricsHAN#2]
Alex, I was going through your code to visualize the attention weights in `attention_vis.py`. Good work and thanks for releasing it.

I notice that you are writing the feed forward equations from the embedding layer onwards to the attention layer - essentially writing the feed forward equations for the entire HAN model. Instead won't it better to obtain the intermediate output of the GRU (h_it) and then write only the attention layer feed forward equations. h_it can be obtained by creating an intermediate model and calling it as follows:

`layer_name = 'GRU'`
`intermediate_layer_model = Model(input=model.input, output=model.get_layer(layer_name).output)`
`intermediate_output = intermediate_layer_model.predict(input_variable)`
`h_it = intermediate_output`

Once h_it is obtained, compute attention weights using the feed forward equations from the call function of attention layer. Did you already think of this and realize something I'm missing currently? Also, do you know of a better way currently?

**Comment by alexTsaptsinos** [comment]
Yes for sure and most probably I should have used Keras to get the weights. I think at that time I was a bit pressed for time and knew I could do it relatively quickly with Python without much thought!

If you're trying to implement this then please let me know if it works!
