### ISSUE TITLE
NaN Loss Despite Clip Norm

### ISSUE THREAD

**Issue by Helw150** [alexTsaptsinos/lyricsHAN#3]
Hi!

I am trying to perform HAN classification, but I am running into NaN loss despite having clipnorm set as in your code. Did you come across this issue and if so how did you solve it?

Thanks!

**Comment by alexTsaptsinos** [comment]
I never came across any NaN loss issues sorry! Are you sure it's due to exploding gradient?

**Comment by Helw150** [comment]
I don't think so now, I believe it must be due to some sort of pre-processing error since I am using my own preprocessing to get the structure. Thanks anyways.

**Comment by Helw150** [comment]
Ah, the issue is due to empty padding. If there is a row that is entirely made up of zeros, the loss is driven to NaN. You mention masking in your implementation, but I don't see where it is implemented.
